export const instructor = {
  name: "小Z",
  avatar: "/assets/faculty-avatar.png",
  stats: [
    ["10", "年", "数字产品与AI落地经验"],
    ["40", "+", "个交付并上线的项目"],
  ],
  highlights: [
    "从代码到影像，AI 全链路",
    "主导 AI 产品从 0 到 1 上线",
    "构建可落地的多智能体系统",
    "用 AI 完成电影级视觉叙事",
    "相信「用得上」才算学会",
  ],
  closing: ["不止学会使用 AI，", "更要用 AI 创造作品。"],
  expertise: [
    ["AI 全栈开发", "Full-Stack AI Engineering"],
    ["Agent 系统架构", "Agentic Systems & MCP"],
    ["AI 影视创作", "Generative Cinema"],
    ["AI 剧集与分镜", "AI Series & Storyboarding"],
    ["AI 视觉与海报设计", "Generative Visual Design"],
    ["智能体工作流", "AI-Native Workflow"],
  ],
} as const;

export const facultyModules = [
  {
    name: "认识 AI · 环境搭建",
    day: "第 1 天 · 上午",
    hours: "3 小时",
    learn: "装好 AI 工作台，看懂大模型的能力与边界。",
    out: "跑通的 AI 工作台",
  },
  {
    name: "提示词 · Skill",
    day: "第 1 天 · 下午",
    hours: "3 小时",
    learn: "调好提示词，再把自己的经验写成可复用的 Skill。",
    out: "一个自己的 Skill",
  },
  {
    name: "AI 视觉 · 海报设计",
    day: "第 2 天 · 上午",
    hours: "3 小时",
    learn: "生图、改图、风格锁定与海报排版。",
    out: "主题海报 + 角色设定",
  },
  {
    name: "AI 影视 · 短片",
    day: "第 2 天 · 下午",
    hours: "3 小时",
    learn: "分镜、运镜、角色一致性，再配上配音与主题曲。",
    out: "15–30 秒 AI 短片",
  },
  {
    name: "Vibe Coding · 建站",
    day: "第 3 天 · 上午",
    hours: "3 小时",
    learn: "用对话做网页，Git 存档并部署上线。",
    out: "上线的个人作品站",
  },
  {
    name: "Agent 智能体 · 结课",
    day: "第 3 天 · 下午",
    hours: "3 小时",
    learn: "用 RAG 和工具调用，把个人知识做成能对话的 Agent。",
    out: "个人知识 Agent",
  },
] as const;

export const facultyKit = [
  {
    id: "laptop",
    x: 1,
    y: 36,
    w: 40,
    r: -2,
    arc: 10,
    spin: -120,
    dur: 0.8,
    src: "/assets/faculty-laptop.webp",
  },
  {
    id: "camera",
    x: 46,
    y: 38,
    w: 20,
    r: 3,
    arc: 22,
    spin: 90,
    dur: 0.8,
    src: "/assets/faculty-camera.webp",
  },
  {
    id: "sushi",
    x: 72,
    y: 37,
    w: 23,
    r: -4,
    arc: 26,
    spin: 160,
    dur: 0.85,
    src: "/assets/faculty-sushi.webp",
  },
  {
    id: "vinyl",
    x: 21,
    y: 29,
    w: 28,
    r: -6,
    arc: 30,
    spin: -200,
    dur: 0.85,
    src: "/assets/faculty-vinyl.webp",
  },
  {
    id: "mic",
    x: 21,
    y: 19,
    w: 9,
    r: 8,
    arc: 34,
    spin: 120,
    dur: 0.9,
    src: "/assets/faculty-mic.webp",
  },
  {
    id: "spark",
    x: 4,
    y: 24,
    w: 17,
    r: -8,
    arc: 36,
    spin: -160,
    dur: 0.9,
    src: "/assets/faculty-spark.webp",
  },
  {
    id: "video",
    x: 41,
    y: 19,
    w: 32,
    r: 4,
    arc: 30,
    spin: 60,
    dur: 0.9,
    src: "/assets/faculty-video.webp",
  },
  {
    id: "gpt",
    x: 80,
    y: 21,
    w: 16,
    r: 7,
    arc: 38,
    spin: 200,
    dur: 0.95,
    src: "/assets/faculty-gpt.webp",
  },
] as const;
