export const instructor = {
  name: "小Z",
  avatar: "/assets/faculty-avatar.png",
  stats: [
    ["10", "年", "数字产品与AI落地经验"],
    ["40", "+", "个交付并上线的项目"],
  ],
  highlights: [
    "做过 3 个上线的 AI 产品",
    "不写代码也能搭 Agent",
    "每周靠 Agent 省下 6 小时",
    "带过 2 期实战营，38 名学员",
    "相信「用得上」才算学会",
  ],
  closing: ["把 AI 变成你的日常工具，", "而不是又一个要学的软件。"],
  modules: [0, 1, 2],
} as const;

export const facultyModules = [
  {
    name: "提示词",
    day: "第 1 天 · 上午",
    hours: "3 小时",
    learn: "结构化提问、角色与上下文，让 AI 按格式输出。",
    out: "一份个人提示词库",
  },
  {
    name: "Agent 智能体",
    day: "第 1 天 · 下午",
    hours: "3 小时",
    learn: "理解 Agent 如何拆解任务、调用工具，零代码搭一个工作助手。",
    out: "一个竞品分析 Agent",
  },
  {
    name: "Skill 技能",
    day: "第 2 天 · 上午",
    hours: "3 小时",
    learn: "把做 PPT 的经验写成 Skill，一句话调用、团队共享。",
    out: "一个自己的「PPT 生成」Skill",
  },
  {
    name: "AI 图片",
    day: "第 2 天 · 下午",
    hours: "1.5 小时",
    learn: "画面描述、风格控制与系列感。",
    out: "一组主题海报",
  },
  {
    name: "AI 音乐",
    day: "第 2 天 · 下午",
    hours: "1.5 小时",
    learn: "歌词结构、曲风标签与人声控制。",
    out: "一首原创歌曲",
  },
  {
    name: "AI 视频 · 漫剧",
    day: "第 3 天 · 上午",
    hours: "1.5 小时",
    learn: "剧本、分镜、角色一致性、配音剪辑成片。",
    out: "一集 AI 漫剧",
  },
  {
    name: "数字人",
    day: "第 3 天 · 上午",
    hours: "1.5 小时",
    learn: "数字人形象与声音制作、口播视频与实时对话。",
    out: "一段数字人口播视频",
  },
  {
    name: "Vibe Coding",
    day: "第 3 天 · 下午",
    hours: "1.5 小时",
    learn: "用对话描述需求，让 AI 生成并上线网页和小工具。",
    out: "一个小工具网页",
  },
  {
    name: "无限画布",
    day: "第 3 天 · 下午",
    hours: "1.5 小时",
    learn: "把文字、图片、视频、音乐节点串成流水线。",
    out: "结课作品 + 路演",
  },
] as const;

export const facultyKit = [
  {
    id: "laptop",
    x: 1,
    y: 36,
    w: 40,
    r: -2,
    arc: 10,
    spin: -120,
    dur: 0.8,
    src: "/assets/faculty-laptop.webp",
  },
  {
    id: "camera",
    x: 46,
    y: 38,
    w: 20,
    r: 3,
    arc: 22,
    spin: 90,
    dur: 0.8,
    src: "/assets/faculty-camera.webp",
  },
  {
    id: "sushi",
    x: 72,
    y: 37,
    w: 23,
    r: -4,
    arc: 26,
    spin: 160,
    dur: 0.85,
    src: "/assets/faculty-sushi.webp",
  },
  {
    id: "vinyl",
    x: 21,
    y: 29,
    w: 28,
    r: -6,
    arc: 30,
    spin: -200,
    dur: 0.85,
    src: "/assets/faculty-vinyl.webp",
  },
  {
    id: "mic",
    x: 21,
    y: 19,
    w: 9,
    r: 8,
    arc: 34,
    spin: 120,
    dur: 0.9,
    src: "/assets/faculty-mic.webp",
  },
  {
    id: "spark",
    x: 4,
    y: 24,
    w: 17,
    r: -8,
    arc: 36,
    spin: -160,
    dur: 0.9,
    src: "/assets/faculty-spark.webp",
  },
  {
    id: "video",
    x: 41,
    y: 19,
    w: 32,
    r: 4,
    arc: 30,
    spin: 60,
    dur: 0.9,
    src: "/assets/faculty-video.webp",
  },
  {
    id: "gpt",
    x: 80,
    y: 21,
    w: 16,
    r: 7,
    arc: 38,
    spin: 200,
    dur: 0.95,
    src: "/assets/faculty-gpt.webp",
  },
] as const;
